// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/order/pb/order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderSerivceClient is the client API for OrderSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderSerivceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderSerivceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderSerivceClient(cc grpc.ClientConnInterface) OrderSerivceClient {
	return &orderSerivceClient{cc}
}

func (c *orderSerivceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderSerivce/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSerivceServer is the server API for OrderSerivce service.
// All implementations must embed UnimplementedOrderSerivceServer
// for forward compatibility
type OrderSerivceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	mustEmbedUnimplementedOrderSerivceServer()
}

// UnimplementedOrderSerivceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderSerivceServer struct {
}

func (UnimplementedOrderSerivceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderSerivceServer) mustEmbedUnimplementedOrderSerivceServer() {}

// UnsafeOrderSerivceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderSerivceServer will
// result in compilation errors.
type UnsafeOrderSerivceServer interface {
	mustEmbedUnimplementedOrderSerivceServer()
}

func RegisterOrderSerivceServer(s grpc.ServiceRegistrar, srv OrderSerivceServer) {
	s.RegisterService(&OrderSerivce_ServiceDesc, srv)
}

func _OrderSerivce_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSerivceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderSerivce/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSerivceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderSerivce_ServiceDesc is the grpc.ServiceDesc for OrderSerivce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderSerivce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderSerivce",
	HandlerType: (*OrderSerivceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderSerivce_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/order/pb/order.proto",
}
